name: Dylan Martin Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5602611736394465
title: Dylan Martin Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030305'
    - '#b5b5bf'
    - '#807d8e'
    - '#a1c507'
    - '#d8f18b'
  brandStrength: 0.5
  lightness: 0.5526699831243604
  saturation: 0.054265606217086315
  rhythmicContrast: 0.8849774128757417
purpose: []
